### PR TITLE
Improve German translation

### PR DESCRIPTION
**Pull request by DarkPurpleKnight**
Fix translation and spelling mistakes in German translation.

### CODE REVIEW

**Comment by ShockwaveNN** [comment]
Hi, please change destination branch to develop, we only merge third-party PR's to develop

**Comment by DarkPurpleKnight** [comment]
@ShockwaveNN All right.

**Review by svetlana81 — APPROVED** [review]
Approved

**Comment by ShockwaveNN** [comment]
@DarkPurpleKnight Thank you for your contirbution

**Pull request merged**
